version: 2
jobs:
  test:
    working_directory: ~/pyeactivities
    docker:
      - image: circleci/python:3.7.1
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run:
          name: "Setup Python folder permissions"
          command: |
            sudo chown -R circleci:circleci /usr/local/bin
            sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - restore_cache:
          key: deps-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          name: "Install Pipenv and project dependencies"
          command: |
            sudo pip install pipenv
            pipenv install -d
      - save_cache:
          key: deps-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.7/site-packages"
      - run:
          name: "Run tests"
          command: |
            pipenv run python -m pytest tests --junitxml=test-results/pytest/pytest-report.xml
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
